name: Publish Docker image

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: get_env
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          repository=${{ github.repository }}
          actor=${{ github.actor }}
          IMAGE_NAME=${actor}/${repository##*/}
          echo IMAGE_NAME=$IMAGE_NAME
          echo VERSION=$VERSION
          echo ::set-output name=VERSION::${VERSION}
          echo ::set-output name=IMAGE_NAME::${IMAGE_NAME}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.get_env.outputs.IMAGE_NAME }}:${{ steps.get_env.outputs.VERSION }}
